### ISSUE TITLE
你好，我这儿报 Non-whitespace before first tag错误

### ISSUE THREAD

**Issue by wangzhongjie** [calvinxiao/allinpay#3]
Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: {
    at error (/Users/xxxyyy/Documents/tiancai/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/Users/xxxyyy/Documents/tiancai/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/Users/xxxyyy/Documents/tiancai/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/Users/xxxyyy/Documents/tiancai/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/Users/xxxyyy/Documents/tiancai/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/Users/xxxyyy/Documents/tiancai/node_modules/xml2js/lib/parser.js:5:59)
    at Parser.tryCatcher (/Users/xxxyyy/Documents/tiancai/node_modules/bluebird/js/release/util.js:16:23)
    at Parser.ret [as parseStringAsync] (eval at makeNodePromisifiedEval (/Users/xxxyyy/Documents/tiancai/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at AccountPay._request (/Users/xxxyyy/Documents/tiancai/node_modules/allinpay/libs/account_pay.js:132:38)
    at process._tickCallback (internal/process/next_tick.js:68:7) cause: {}, isOperational: true }

会不会通联那边最近3年修改过加密方式呢？
PS，另外P12私钥文件导出pem文件你用的是什么方法？谢谢

**Comment by calvinxiao** [comment]
> PS，另外P12私钥文件导出pem文件你用的是什么方法？谢谢

看看这个 https://stackoverflow.com/questions/15144046/converting-pkcs12-certificate-into-pem-using-openssl

**Comment by calvinxiao** [comment]
你看看和这个是不是相关的 https://github.com/isaacs/sax-js/issues/138，这个项目没有跟进 allinpay 的文档，而生产环境已经没有在用已经两年多了

**Comment by wangzhongjie** [comment]
已解决，要解析钥匙， 然后 -----BEGIN PRIVATE KEY-----${key}-----END PRIVATE KEY----- 才行，你这个仓库对我帮助很大谢谢
